"""Add committee_decisions and shadow_mode_trades

Revision ID: dbc2b9377763
Revises: b4effa4a3cfc
Create Date: 2026-08-08 19:06:39.263485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbc2b9377763'
down_revision: Union[str, Sequence[str], None] = 'b4effa4a3cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('committee_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('market_regime', sa.String(), nullable=False),
    sa.Column('votes', sa.JSON(), nullable=False),
    sa.Column('consensus_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('final_decision', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('shadow_mode', sa.Boolean(), nullable=False),
    sa.Column('reasoning', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_committee_decisions_symbol'), 'committee_decisions', ['symbol'], unique=False)
    op.create_table('shadow_mode_trades',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('committee_decision_id', sa.Uuid(), nullable=False),
    sa.Column('rule_based_decision', sa.String(), nullable=False),
    sa.Column('entry_price', sa.Numeric(), nullable=True),
    sa.Column('exit_price', sa.Numeric(), nullable=True),
    sa.Column('pnl_pct', sa.Numeric(), nullable=True),
    sa.Column('max_adverse_excursion', sa.Numeric(), nullable=True),
    sa.Column('regime_at_entry', sa.String(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['committee_decision_id'], ['committee_decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shadow_mode_trades')
    op.drop_index(op.f('ix_committee_decisions_symbol'), table_name='committee_decisions')
    op.drop_table('committee_decisions')
    # ### end Alembic commands ###
